### ISSUE TITLE
Must have a permission set

### ISSUE THREAD

**Issue by AraaCuteUwU** [dhnnz/Market#1]
A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: Market

Error: Commands must have a permission set
File: pmsrc/src/command/SimpleCommandMap
Line: 143
Type: InvalidArgumentException
Backtrace:
#0 plugins/Market/src/dhnnz/Market/Loader(41): pocketmine\command\SimpleCommandMap->register(string[7] Markets, object dhnnz\Market\commands\MarketCommand#58323, string[6] market)
#1 pmsrc/src/plugin/PluginBase(118): dhnnz\Market\Loader->onEnable()
#2 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#3 pmsrc/src/Server(1382): pocketmine\plugin\PluginManager->enablePlugin(object dhnnz\Market\Loader#46787)
#4 pmsrc/src/Server(1035): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#46439)
#5 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#5, string[15] /root/survival/, string[23] /root/survival/plugins/)
#6 pmsrc/src/PocketMine(362): pocketmine\server()
#7 pmsrc(11): require(string[59] phar:///root/survival/PocketMine-MP.phar/src/PocketMine.php)

**Comment by dhnnz** [comment]
Hi [AraaCuteUwU](https://github.com/AraaCuteUwU), thank you for reporting this issue. I have fixed the "Must have a permission set" problem you found, and I have merged the fix into the latest commit at https://github.com/dhnnz/Market/commit/af1f76c43930c2db566a840b7973b6578e63854d. Please give it a try and let me know if the issue still persists. Thank you for your contribution."

I hope this helps!
