### ISSUE TITLE
DiscordWebhookError

### ISSUE THREAD

**Issue by AzOxStOz** [dhnnz/Market#3]
pmmp\thread\NonThreadSafeValueError: "Cannot assign non-thread-safe value of type dhnnz\Market\libs\webhook\Webhook to thread-safe class property dhnnz\Market\task\DiscordWebhookSendTask::$webhook

When a message is send it does that.

**Comment by AzOxStOz** [comment]
*PM5

**Comment by dhnnz** [comment]
https://github.com/dhnnz/Market/commit/1674b691af32d07429f27697fb54cf4b5544ab2a
