### ISSUE TITLE
Error when I sell item

### ISSUE THREAD

**Issue by NdaruAjaa** [dhnnz/Market#4]
PocketMine-MP version: 5.1.2 [Protocol 589]
Git commit: 7cd317bf398a017f7c690a475c5a67650c610323
PHP version: 8.1.19
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: Market

Error: json_encode()ing Item instances is no longer supported. Make your own method to convert the item to an array or stdClass.
File: pmsrc/src/item/Item
Line: 664
Type: LogicException
Backtrace:
#0 plugins/Market_dev-21.phar/src/dhnnz/Market/forms/FormManager(315): pocketmine\item\Item->jsonSerialize()
#1 plugins/Market_dev-21.phar/src/dhnnz/Market/libs/jojoe77777/FormAPI/Form(46): dhnnz\Market\forms\FormManager->dhnnz\Market\forms\{closure}(object pocketmine\player\Player#151687, array[5])
#2 pmsrc/src/player/Player(2117): dhnnz\Market\libs\jojoe77777\FormAPI\Form->handleResponse(object pocketmine\player\Player#151687, array[5])
#3 pmsrc/src/network/mcpe/handler/InGamePacketHandler(970): pocketmine\player\Player->onFormSubmit(int 2, array[5])
#4 pmsrc/vendor/pocketmine/bedrock-protocol/src/ModalFormResponsePacket(63): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#70812)
#5 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#86193)
#6 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#70812, string[31] e...[null,0,"1","1000",false]..)
#7 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[32] .Oeb...+...1.Q2T.b...%......X...)
#8 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[41] .  W.)........`..4.s..=.3.#....*.O:....Aq)
#9 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#195625)
#10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#13 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1688024127.3892)
#14 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#15 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#16 pmsrc/src/PocketMine(357): pocketmine\server()
#17 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by dhnnz** [comment]
https://github.com/dhnnz/Market/commit/1c638b4a9b02031c94fc2d4ebbd0cdaeadfafd1f
