### ISSUE TITLE
WebhookErrorStillHere

### ISSUE THREAD

**Issue by AzOxStOz** [dhnnz/Market#5]
The error is still here

**Comment by AzOxStOz** [comment]
TypeError: "Cannot assign dhnnz\Market\libs\webhook\Message to property dhnnz\Market\task\DiscordWebhookSendTask::$message of type string"

**Comment by dhnnz** [comment]
https://github.com/dhnnz/Market/commit/cf61f91a2f510eddf0709169687c80b132eacd3b
